import type { BeamAsset } from '@/lib/useAcquisitionSites'

const emptyScores = {
  capacity: 0,
  impact: 0,
  stability: 0,
  revenue: 0,
  partner: 0,
}

export const seededPublicProperties: BeamAsset[] = [
  {
    id: 'seed-cumc',
    name: 'Central United Methodist Church',
    publicTitle: 'Central United Methodist Church',
    publicSummary:
      'A historic sanctuary being evaluated as a shared civic anchor - housing, workforce training, and neighborhood services under one roof.',
    address: '639 N 25th St, Milwaukee, WI',
    regionId: 'milwaukee-wi',
    publicVisible: true,
    ownerName: 'United Methodist Church of Wisconsin',
    acquisitionStage: 'SIGNAL',
    condition: 'unknown',
    operatorNarrative: '',
    locationType: 'civic-anchor',
    stewardshipStatus: 'observed',
    primaryUseCases: ['Affordable housing', 'Trade-skills workshop', 'Community kitchen', 'Performance hall'],
    ngoLinks: [
      {
        ngoId: 'architecture',
        ngoName: 'BEAM Architecture',
        ngoSubdomain: 'architecture.beamthinktank.space',
        relationshipType: 'cohort-project',
        linkedAt: '2026-06-01T00:00:00Z',
      },
      {
        ngoId: 'forge',
        ngoName: 'BEAM Forge',
        ngoSubdomain: 'forge.beamthinktank.space',
        relationshipType: 'cohort-project',
        linkedAt: '2026-06-01T00:00:00Z',
      },
    ],
    cohortPool: 'acquisition',
    tenants: [
      {
        name: 'Central United Methodist Church',
        category: 'religious',
        status: 'current',
        websiteUrl: 'https://centralumcmilwaukee.org',
        notes: '',
      },
    ],
    ckanOwnerName: 'United Methodist Church of Wisconsin',
    ckanZoning: 'RT4',
    ckanTaxStatus: 'exempt',
    ckanAssessedValue: 0,
    scores: emptyScores,
    stageHistory: [],
    linkedProjectIds: [],
    linkedActionIds: [],
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'seed-mpm',
    name: 'Former Milwaukee Public Museum',
    publicTitle: 'Former Milwaukee Public Museum',
    publicSummary:
      'A 417,000 sq ft civic institution closing in January 2027. BEAM is positioning for a joint adaptive reuse submission with UWM and MATC.',
    address: '800 W Wells St, Milwaukee, WI',
    regionId: 'milwaukee-wi',
    publicVisible: true,
    ownerName: 'Milwaukee County',
    acquisitionStage: 'CLAIM',
    condition: 'unknown',
    operatorNarrative: '',
    locationType: 'civic-anchor',
    stewardshipStatus: 'unmonitored',
    primaryUseCases: ['24-hr research library', 'Fabrication lab', 'Performance venue', 'Affordable housing'],
    ngoLinks: [
      {
        ngoId: 'grounds',
        ngoName: 'BEAM Grounds',
        ngoSubdomain: 'grounds.beamthinktank.space',
        relationshipType: 'anchor-site',
        linkedAt: '2026-06-01T00:00:00Z',
      },
      {
        ngoId: 'finance',
        ngoName: 'BEAM Finance',
        ngoSubdomain: 'finance.beamthinktank.space',
        relationshipType: 'service-site',
        linkedAt: '2026-06-01T00:00:00Z',
      },
    ],
    cohortPool: 'acquisition',
    scores: emptyScores,
    stageHistory: [],
    linkedProjectIds: [],
    linkedActionIds: [],
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'seed-mpl',
    name: 'Milwaukee Public Library - Central Branch Model',
    publicTitle: 'Milwaukee Public Library - Central Branch Model',
    publicSummary:
      "Milwaukee Public Library's bond-financed civic anchor precedent: library and affordable housing in a single mixed-use structure.",
    address: '814 W Wisconsin Ave, Milwaukee, WI',
    regionId: 'milwaukee-wi',
    publicVisible: true,
    ownerName: 'City of Milwaukee',
    acquisitionStage: 'ACTIVATE',
    condition: 'unknown',
    operatorNarrative: '',
    locationType: 'civic-anchor',
    stewardshipStatus: 'activated',
    primaryUseCases: ['Library branch', 'Affordable housing', 'Community meeting space'],
    ngoLinks: [
      {
        ngoId: 'finance',
        ngoName: 'BEAM Finance',
        ngoSubdomain: 'finance.beamthinktank.space',
        relationshipType: 'service-site',
        linkedAt: '2026-06-01T00:00:00Z',
      },
      {
        ngoId: 'grounds',
        ngoName: 'BEAM Grounds',
        ngoSubdomain: 'grounds.beamthinktank.space',
        relationshipType: 'anchor-site',
        linkedAt: '2026-06-01T00:00:00Z',
      },
    ],
    cohortPool: 'financing',
    scores: emptyScores,
    stageHistory: [],
    linkedProjectIds: [],
    linkedActionIds: [],
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
]

