/**
 * Seed script for Track A, B, C, and D asset examples.
 * Usage: npx tsx scripts/seed-tracks.ts
 */

export const SEEDED_TRACK_ASSETS = [
  {
    id: 'asset-track-a-supportive',
    name: 'North Avenue Supportive Haven',
    address: '1420 W North Ave, Milwaukee, WI',
    regionId: 'mke-urban',
    ownerName: 'BEAM Grounds Land Trust (Supportive Housing NSP)',
    acquisitionTrack: 'A',
    acquisitionStage: 'STABILIZE',
    condition: 'fair',
    operatorNarrative: 'Track A HUD Section 202 / PRAC supportive residential project. Provides 12 rent-free housing units for at-risk neighbors.',
    primaryUseCases: ['Supportive Housing', 'Community Services'],
    scores: { capacity: 4, impact: 5, stability: 4, revenue: 1, partner: 5 },
    stageHistory: [
      { stage: 'SIGNAL', timestamp: '2026-01-15T00:00:00Z', note: 'HUD PRAC grant awarded' },
      { stage: 'STABILIZE', timestamp: '2026-04-10T00:00:00Z', note: 'Essential repair sprint completed' },
    ],
    linkedProjectIds: [],
    linkedActionIds: [],
    publicVisible: true,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'asset-track-b-cultural',
    name: 'Vliet Street Assembly & Cultural Hall',
    address: '3817 W Vliet St, Milwaukee, WI',
    regionId: 'mke-urban',
    ownerName: 'BEAM Grounds Non-Profit Land Trust',
    acquisitionTrack: 'B',
    acquisitionStage: 'ACTIVATE',
    condition: 'good',
    operatorNarrative: 'Track B civic & cultural adaptive reuse project. Features performance venue, rehearsal rooms, and community assembly hall.',
    primaryUseCases: ['Performance Venue', 'Rehearsal Space', 'Civic Anchor'],
    scores: { capacity: 5, impact: 5, stability: 3, revenue: 2, partner: 5 },
    stageHistory: [
      { stage: 'SIGNAL', timestamp: '2026-02-01T00:00:00Z', note: 'Civic scan imported' },
      { stage: 'ACTIVATE', timestamp: '2026-06-01T00:00:00Z', note: 'Orchestra & Dance cohort active' },
    ],
    linkedProjectIds: [],
    linkedActionIds: [],
    publicVisible: true,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'asset-track-c-commercial',
    name: 'Wells Street Mixed Commercial & Lofts',
    address: '800 W Wells St, Milwaukee, WI',
    regionId: 'mke-urban',
    ownerName: 'Wells Street Real Estate Holdings LLC',
    acquisitionTrack: 'C',
    acquisitionStage: 'CLAIM',
    condition: 'good',
    operatorNarrative: 'Track C market-rate commercial and residential development. Conventional debt + equity structure for ground floor retail and upper lofts.',
    primaryUseCases: ['Mixed-Use Commercial', 'Market-Rate Housing'],
    scores: { capacity: 4, impact: 3, stability: 4, revenue: 5, partner: 3 },
    stageHistory: [
      { stage: 'SIGNAL', timestamp: '2026-03-01T00:00:00Z', note: 'Title evaluation' },
      { stage: 'CLAIM', timestamp: '2026-05-15T00:00:00Z', note: 'Purchase agreement executed' },
    ],
    linkedProjectIds: [],
    linkedActionIds: [],
    publicVisible: true,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-05-15T00:00:00Z',
  },
  {
    id: 'asset-track-d-production',
    name: 'Kinnickinnic Industrial & Organic Production Hub',
    address: '2200 S Kinnickinnic Ave, Milwaukee, WI',
    regionId: 'mke-industrial',
    ownerName: 'BEAM Manufacturing & Forge Ops LLC',
    acquisitionTrack: 'D',
    productionLane: 'organic',
    acquisitionStage: 'ACCESS',
    condition: 'fair',
    operatorNarrative: 'Track D production facility with dual organic (food/cosmetics) and industrial (apparel/electronics) manufacturing lanes.',
    primaryUseCases: ['Organic Food Processing', 'Industrial Production Hub'],
    scores: { capacity: 5, impact: 4, stability: 3, revenue: 4, partner: 4 },
    stageHistory: [
      { stage: 'SIGNAL', timestamp: '2026-04-01T00:00:00Z', note: 'Environmental site assessment' },
      { stage: 'ACCESS', timestamp: '2026-07-20T00:00:00Z', note: 'Health dept & zoning permit review' },
    ],
    linkedProjectIds: [],
    linkedActionIds: [],
    publicVisible: true,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
  },
]
